### ISSUE TITLE
Next Hugging Face not creating project

### ISSUE THREAD

**Issue by maotoledo** [vercel-labs/ai#116]
Running on macos m1
```
npx create-next-app --example https://github.com/vercel-labs/ai/tree/main/examples/next-huggingface next-huggingface-app
```

Returns error:
```
npx: installed 1 in 1.664s

Aborting installation.
Unexpected error. Please report it as a bug:
 { Error: EEXIST: file already exists, mkdir '/Users/me/Library/Preferences/create-next-app-nodejs'
    at Object.fs.mkdirSync (fs.js:840:3)
    at Conf._ensureDirectory (/Users/me/.npm/_npx/33439/lib/node_modules/create-next-app/dist/index.js:38:34811)
    at Conf.get store [as store] (/Users/me/.npm/_npx/33439/lib/node_modules/create-next-app/dist/index.js:38:33449)
    at Conf._get (/Users/me/.npm/_npx/33439/lib/node_modules/create-next-app/dist/index.js:38:36766)
    at Conf.get (/Users/me/.npm/_npx/33439/lib/node_modules/create-next-app/dist/index.js:38:31582)
    at run (/Users/me/.npm/_npx/33439/lib/node_modules/create-next-app/dist/index.js:325:26974)
    at Module.68994 (/Users/me/.npm/_npx/33439/lib/node_modules/create-next-app/dist/index.js:325:30991)
    at __nccwpck_require__ (/Users/me/.npm/_npx/33439/lib/node_modules/create-next-app/dist/index.js:325:38793)
    at /Users/me/.npm/_npx/33439/lib/node_modules/create-next-app/dist/index.js:325:39657
    at Object.<anonymous> (/Users/me/.npm/_npx/33439/lib/node_modules/create-next-app/dist/index.js:325:39702)
  errno: -17,
  syscall: 'mkdir',
  code: 'EEXIST',
  path: '/Users/me/Library/Preferences/create-next-app-nodejs' }
```

**Comment by MaxLeiter** [comment]
```
Error: EEXIST: file already exists, mkdir '/Users/me/Library/Preferences/create-next-app-nodejs'
```

It seems like you already have a directory with that name present. Can you try removing that? Also, you may want to work from inside `Documents` instead of `Library/Preferences`.

**Comment by maotoledo** [comment]
@MaxLeiter my bad, I was using an older version of node. Now working with LTS.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The reported failure was caused by the local Node.js environment and was resolved without any change to the AI SDK or its example.

### Evidence
- The failure occurred in create-next-app while creating its preferences directory, before the example project was installed.
- The reporter confirmed they were using an older Node.js version and that switching to Node.js LTS resolved the problem.
