### ISSUE TITLE
Stream Issue

### ISSUE THREAD

**Issue by GavanWilhite** [vercel-labs/ai#292]
I get this rather obscure error message when I return the StreamingTextResponse:

```
- error unhandledRejection: Error [TypeError]: Cannot read properties of undefined (reading '0')
    at eval (webpack-internal:///(middleware)/./node_modules/.pnpm/ai@2.1.14_react@18.2.0_svelte@3.59.2_vue@3.3.4/node_modules/ai/dist/index.mjs:138:43)
    at eval (webpack-internal:///(middleware)/./node_modules/.pnpm/ai@2.1.14_react@18.2.0_svelte@3.59.2_vue@3.3.4/node_modules/ai/dist/index.mjs:73:47)
    at parseEventStreamLine (webpack-internal:///(middleware)/./node_modules/.pnpm/eventsource-parser@1.0.0/node_modules/eventsource-parser/dist/index.js:77:17)
    at Object.feed (webpack-internal:///(middleware)/./node_modules/.pnpm/eventsource-parser@1.0.0/node_modules/eventsource-parser/dist/index.js:65:13)
    at Object.transform (webpack-internal:///(middleware)/./node_modules/.pnpm/ai@2.1.14_react@18.2.0_svelte@3.59.2_vue@3.3.4/node_modules/ai/dist/index.mjs:80:31)
    at g (eval at requireWithFakeGlobalScope (/Users/gavan/Projects/chatmsd/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334), <anonymous>:102:35)
    at w (eval at requireWithFakeGlobalScope (/Users/gavan/Projects/chatmsd/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334), <anonymous>:107:14)
    at Object.eval [as transform] `(eval` at requireWithFakeGlobalScope (/Users/gavan/Projects/chatmsd/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334), <anonymous>:1953:33)
    at TransformStreamDefaultController.eval (eval at requireWithFakeGlobalScope (/Users/gavan/Projects/chatmsd/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334), <anonymous>:2063:49)
    at pr (eval at requireWithFakeGlobalScope (/Users/gavan/Projects/chatmsd/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334), <anonymous>:2181:15) {
  digest: undefined
```

This is in a local "edge function". It seems to have randomly started happening. Maybe it's some sort of error or warning from OpenAI?

**Comment by brerdem** [comment]
This seems svelte dependency issue. I had the same problem then I switched from `npm` to `yarn` and it went away.

**Comment by MaxLeiter** [comment]
This should be resolved in the next release

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The report describes an unexpected runtime failure in existing streaming behavior, and the planned release fix confirms it as a product defect.

### Evidence
- Returning `StreamingTextResponse` in a local edge function throws an unhandled `TypeError` inside `ai@2.1.14`.
- A maintainer stated that the issue should be resolved in the next release.
