### ISSUE TITLE
use vercel ai sdk with next.js 12

### ISSUE THREAD

**Issue by onlyrandomguy** [vercel-labs/ai#316]
Hey! I can't seem to figure out how to specify the api option for the vercel ai sdk when using next.js 12. The route defaults to api/chat and it works perfectly for next.js 13. Every time I specify a custom route for the option when using next.js 12, I get the following error:

```
ncaught (in promise) Error: <!DOCTYPE html><html lang="en"><head><style data-next-hide-fouc="true">body{display:none}</style><noscript data-next-hide-fouc="true"><style>body{display:block}</style></noscript><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><title>404: This page could not be found</title><meta name="next-head-count" content="3"/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills.js?ts=1689034684232"></script><script src="/_next/static/chunks/webpack.js?ts=1689034684232" defer=""></script><script src="/_next/static/chunks/main.js?ts=1689034684232" defer=""></script><script src="/_next/static/chunks/pages/_app.js?ts=1689034684232" defer=""></script><script src="/_next/static/chunks/pages/_error.js?ts=1689034684232" defer=""></script><script src="/_next/static/development/_buildManifest.js?ts=1689034684232" defer=""></script><script src="/_next/static/development/_ssgManifest.js?ts=1689034684232" defer=""></script><noscript id="__next_css__DO_NOT_USE__"></noscript></head><body><div id="__next"><div style="font-family:system-ui,&quot;Segoe UI&quot;,Roboto,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center"><div style="line-height:48px"><style>body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}</style><h1 class="next-error-h1" style="display:inline-block;margin:0 20px 0 0;padding-right:23px;font-size:24px;font-weight:500;vertical-align:top">404</h1><div style="display:inline-block"><h2 style="font-size:14px;font-weight:400;line-height:28px">This page could not be found<!-- -->.</h2></div></div></div></div><script src="/_next/static/chunks/react-refresh.js?ts=1689034684232"></script><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":404}},"page":"/_error","query":{},"buildId":"development","isFallback":false,"gip":true,"scriptLoader":[]}</script></body></html>
    at eval (index.mjs:97:1)
    at Generator.next (<anonymous>)
    at fulfilled (index.mjs:22:1)
eval @ index.mjs:97
fulfilled @ index.mjs:22
```

**Comment by MaxLeiter** [comment]
Hi,

It seems like the hook is encountering a 404. Are you sure you have a `pages/api` function as expected? Can you share a repo?

**Comment by onlyrandomguy** [comment]
Hey - the exact route that I defined the function in was `pages/api/chat/route.js`. I also basically copied the example from the example implementation in source code, since I am still testing AI chat capabilities for our product that's using next.js 12.

**Comment by MaxLeiter** [comment]
Ah, I think you're using an App Router Route Handler in the `pages` directory. Your file should be `pages/api/chat.tsx` (or `pages/api/chat/index.tsx`. Can you share the code so I can confirm its for the correct router?

**Comment by onlyrandomguy** [comment]
Implementation with exact path:

```
'use client'

import { useChat } from 'ai/react'

export default function Chat() {
  const { messages, input, handleInputChange, handleSubmit } = useChat({api: '{{route}}')

  return (
    <div className="flex flex-col w-full max-w-md py-24 mx-auto stretch">
      {messages.length > 0
        ? messages.map(m => (
            <div key={m.id} className="whitespace-pre-wrap">
              {m.role === 'user' ? 'User: ' : 'AI: '}
              {m.content}
            </div>
          ))
        : null}

      <form onSubmit={handleSubmit}>
        <input
          className="fixed bottom-0 w-full max-w-md p-2 mb-8 border border-gray-300 rounded shadow-xl"
          value={input}
          placeholder="Say something..."
          onChange={handleInputChange}
        />
      </form>
    </div>
  )
}
```

I tried a bunch of different paths including pages/api/chat.tsx and tried all sorts of permutations for the path.

**Comment by MaxLeiter** [comment]
I need to see your API route

**Comment by onlyrandomguy** [comment]
Tried both:
pages/api/chat/route.js
pages/api/chat.js (where I didn't create the folder and just had a file)

**Comment by onlyrandomguy** [comment]
```
import { Configuration, OpenAIApi } from 'openai-edge'
import { OpenAIStream, StreamingTextResponse } from 'ai'

// Create an OpenAI API client (that's edge friendly!)
const config = new Configuration({
  apiKey: process.env.OPENAI_API_KEY
})
const openai = new OpenAIApi(config)

// IMPORTANT! Set the runtime to edge
export const runtime = 'edge'

export async function POST(req) {
  // Extract the `prompt` from the body of the request
  const { messages } = await req.json()

  // Ask OpenAI for a streaming chat completion given the prompt
  const response = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo-0613',
    stream: true,
    messages: messages.map((message) => ({
      content: message.content,
      role: message.role
    }))
  })

  // Convert the response into a friendly text-stream
  const stream = OpenAIStream(response)
  // Respond with the stream
  return new StreamingTextResponse(stream)
}
```
Basically the same as the vercel example, but js

**Comment by MaxLeiter** [comment]
yeah so the example you're using is for the App Router only available in Next.js 13. Take a look here instead: https://sdk.vercel.ai/docs/guides/nextjs-pages

**Comment by onlyrandomguy** [comment]
Oh, that makes sense - thanks a lot!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a support/configuration question caused by mixing App Router and Pages Router conventions, not a defect or requested documentation change.

### Evidence
- The reporter used a Next.js 13 App Router-style route handler inside a Next.js 12 Pages Router project.
- A maintainer directed them to the existing Next.js Pages Router guide, and the reporter confirmed that resolved the confusion.
