### ISSUE TITLE
[Bug] Cannot run svelte example app

### ISSUE THREAD

**Issue by ryoppippi** [vercel-labs/ai#317]
When I launch it, it says like 

```sh
Internal server error: Cannot find module 'ai/svelte' imported from '/private/tmp/ai/examples/sveltekit-openai/src/routes/+page.svelte'
      at nodeImport (file:///private/tmp/ai/node_modules/.pnpm/vite@4.3.9_@types+node@20.0.0/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54441:25)
      at ssrImport (file:///private/tmp/ai/node_modules/.pnpm/vite@4.3.9_@types+node@20.0.0/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54343:30)
      at eval (/private/tmp/ai/examples/sveltekit-openai/src/routes/+page.svelte:4:37)
      at async instantiateModule (file:///private/tmp/ai/node_modules/.pnpm/vite@4.3.9_@types+node@20.0.0/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54405:9) (x3)
Error: Cannot find module 'ai/svelte' imported from '/private/tmp/ai/examples/sveltekit-openai/src/routes/+page.svelte'
    at nodeImport (file:///private/tmp/ai/node_modules/.pnpm/vite@4.3.9_@types+node@20.0.0/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54441:25)
    at ssrImport (file:///private/tmp/ai/node_modules/.pnpm/vite@4.3.9_@types+node@20.0.0/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54343:30)
    at eval (/private/tmp/ai/examples/sveltekit-openai/src/routes/+page.svelte:4:37)
    at async instantiateModule (file:///private/tmp/ai/node_modules/.pnpm/vite@4.3.9_@types+node@20.0.0/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54405:9) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by ryoppippi** [comment]
Okay, it works when I copy the directory to another space.
It's kind a weird

**Comment by MaxLeiter** [comment]
Are you trying to run the example where `pnpm` installed it? You likely lack the permissions necessary in`/private/tmp`.

**Comment by BEpresent** [comment]
Got the same error using `pnpm install`, it works with `npm install` though. Not sure if it's an pnpm issue ?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The repository’s existing Svelte example fails to run under the documented development setup due to module resolution, which is a concrete broken behavior.

### Evidence
- Launching the SvelteKit example fails with `ERR_MODULE_NOT_FOUND` for `ai/svelte`.
- A second user reproduced the failure after `pnpm install`, while reporting that `npm install` works.
- Changing the directory or package manager avoids the error, indicating a concrete installation or module-resolution failure.
