### ISSUE TITLE
OpenAI Completions API - 404 Error

### ISSUE THREAD

**Issue by phenomen** [vercel-labs/ai#61]
I was following the guide in the docs, but can't make it work. The response to Completion API always has status 404.

`/routes/api/completion/+server.ts`
```ts
import { OPENAI_API_KEY } from '$env/static/private';

import { Configuration, OpenAIApi } from 'openai-edge';
import { OpenAIStream, StreamingTextResponse } from 'ai';

import type { RequestHandler } from './$types';

const config = new Configuration({
	apiKey: OPENAI_API_KEY
});
const openai = new OpenAIApi(config);

export const POST = (async ({ request }) => {
	const { prompt } = await request.json();

	const response = await openai.createCompletion({
		model: 'gpt-3.5-turbo',
		stream: true,
		prompt: prompt
	});

	const stream = OpenAIStream(response);

	return new StreamingTextResponse(stream);
}) satisfies RequestHandler;
```

Error:
```
Response {
  [Symbol(realm)]: null,
  [Symbol(state)]: {
    aborted: false,
    rangeRequested: false,
    timingAllowPassed: true,
    requestIncludesCredentials: true,
    type: 'default',
    status: 404,
    timingInfo: {
      startTime: 808392.5959000029,
      redirectStartTime: 0,
      redirectEndTime: 0,
      postRedirectStartTime: 808392.5959000029,
      finalServiceWorkerStartTime: 0,
      finalNetworkResponseStartTime: 0,
      finalNetworkRequestStartTime: 0,
      endTime: 0,
      encodedBodySize: 153,
      decodedBodySize: 0,
      finalConnectionTimingInfo: null
    },
    cacheState: '',
    statusText: 'Not Found',
    headersList: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    urlList: [ [URL] ],
    body: { stream: undefined }
  },
  [Symbol(headers)]: HeadersList {
    cookies: null,
    [Symbol(headers map)]: Map(21) {
      'date' => [Object],
      'content-type' => [Object],
      'transfer-encoding' => [Object],
      'connection' => [Object],
      'access-control-allow-origin' => [Object],
      'openai-organization' => [Object],
      'openai-processing-ms' => [Object],
      'openai-version' => [Object],
      'strict-transport-security' => [Object],
      'x-ratelimit-limit-requests' => [Object],
      'x-ratelimit-limit-tokens' => [Object],
      'x-ratelimit-remaining-requests' => [Object],
      'x-ratelimit-remaining-tokens' => [Object],
      'x-ratelimit-reset-requests' => [Object],
      'x-ratelimit-reset-tokens' => [Object],
      'x-request-id' => [Object],
      'cf-cache-status' => [Object],
      'server' => [Object],
      'cf-ray' => [Object],
      'content-encoding' => [Object],
      'alt-svc' => [Object]
    },
    [Symbol(headers map sorted)]: null
  }
}
Error: Failed to convert the response to stream. Received status code: 404.
    at Module.AIStream (D:/Github/bard/node_modules/.pnpm/ai@2.0.0_react@18.2.0_svelte@3.59.1/node_modules/ai/dist/chunk-265FSSO4.mjs:74:11)
    at Module.OpenAIStream (D:/Github/bard/node_modules/.pnpm/ai@2.0.0_react@18.2.0_svelte@3.59.1/node_modules/ai/dist/chunk-TJMME6CL.mjs:19:32)
    at POST (D:/Github/bard/src/routes/api/completion/+server.ts:21:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.render_endpoint (D:/Github/bard/node_modules/.pnpm/@sveltejs+kit@1.20.2_svelte@3.59.1_vite@4.3.9/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:47:18)
    at async resolve (D:/Github/bard/node_modules/.pnpm/@sveltejs+kit@1.20.2_svelte@3.59.1_vite@4.3.9/node_modules/@sveltejs/kit/src/runtime/server/respond.js:403:17)
    at async Module.respond (D:/Github/bard/node_modules/.pnpm/@sveltejs+kit@1.20.2_svelte@3.59.1_vite@4.3.9/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:20)
    at async file:///D:/Github/bard/node_modules/.pnpm/@sveltejs+kit@1.20.2_svelte@3.59.1_vite@4.3.9/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:505:22
```

**Comment by shuding** [comment]
`gpt-3.5-turbo` isn't a completion model, so you can't use it with `openai.createCompletion` and OpenAI is returning 404. More info: https://platform.openai.com/docs/models/model-endpoint-compatibility

```js
	const response = await openai.createCompletion({
		model: 'gpt-3.5-turbo',
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a usage/support issue caused by selecting a model incompatible with the chosen OpenAI endpoint, not a failure of the AI SDK or an explicit request to change documentation.

### Evidence
- The request uses `gpt-3.5-turbo` with `openai.createCompletion`.
- A maintainer explains that `gpt-3.5-turbo` is not compatible with the Completions endpoint, so OpenAI returns the 404.
